"""
NIGERIA COMPARISON: NO-ROAD BASELINE OPTIMISATION
-------------------------------------------------

Purpose
-------
Runs surveillance site optimisation for Nigerian state landscapes without
any road-accessibility constraints.

This provides an idealised benchmark against which road-constrained
optimisation results can be compared.

This script is part of the Nigeria comparison analysis conducted to contrast
road accessibility effects between Nigeria and DRC (see manuscript).

Inputs
------
- Host distribution (.joblib)
- Simulation outputs generated by run_sims_nigeria.py

Command-line arguments
----------------------
STATE_ID       : state identifier (e.g. "ABIA")
SURVEY_FREQ    : survey frequency (integer)
NSITES         : number of surveillance sites (integer)

Example:
    python optimise_sites_no_roads_nigeria.py ABIA 104 10

Outputs
-------
Writes optimisation traces, configurations and metrics to:
    nigeria_comparison/Outputs/optimisation/
"""

import os
#os.environ["OMP_NUM_THREADS"] = "1"  # limit each process to 1 thread
#os.environ["OPENBLAS_NUM_THREADS"] = "1"
#os.environ["MKL_NUM_THREADS"] = "1"
import sys
from pathlib import Path
THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[4]  # adjust if needed
sys.path.insert(0, str(PROJECT_ROOT))

#ROAD_JA = sys.argv[1]  #20p, 30p, 40p
AREA_JA = sys.argv[1]
SURVEY_FREQ_JA = int(sys.argv[2])  # 52, 26, 17 (once a year, twice a year, thrice a year)
NSITES_JA=int(sys.argv[3])  # 5, 10, 15
#P_DETECT_JA = float(sys.argv[1])  # 0.25, 0.5, 0.75, or 0.9  (job array values used for P_DETECT)

task_id = os.environ.get('SLURM_ARRAY_TASK_ID')


from CONSTANT import ALPHA, BETA, SIGMA0, LOGISTIC_RATE, PREVALENCE, P_DETECT, NTREES_SURVEY, SURVEY_FREQ, NSITES
from optimisation_nigeria import site_loc_allowed, logistic_forOpt, objective_more_optimised, simulated_annealing, opt_metrics
import numpy as np
import matplotlib.pyplot as plt
import datetime
from joblib import dump, load
import geopandas as gpd


### change: SURVEY_FREQ, saved file names/directory, number of simulations used

# Base directory for Nigeria comparison workflow
BASE_DIR = PROJECT_ROOT / "main_analysis" / "code" / "nigeria_comparison"

# Inputs
INPUT_HOST = BASE_DIR / "host_distributions"

# Simulation outputs
SIM_OUTPUT_DIR = BASE_DIR / "Outputs" / "simulations"

# Optimisation outputs
OUTPUT_DIR = BASE_DIR / "Outputs" / "optimisation"
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

TRACE_DIR = OUTPUT_DIR / "output_trace"
CONFIG_DIR = OUTPUT_DIR / "output_config"
METRIC_DIR = OUTPUT_DIR / "output_metric"
MAP_DIR = OUTPUT_DIR / "output_map"

TRACE_DIR.mkdir(parents=True, exist_ok=True)
CONFIG_DIR.mkdir(parents=True, exist_ok=True)
METRIC_DIR.mkdir(parents=True, exist_ok=True)
MAP_DIR.mkdir(parents=True, exist_ok=True)

# Filenames
filename_sim = f"df_sims{AREA_JA}.joblib"
filename_save = f"NoRoad_{AREA_JA}_surveyfreq{SURVEY_FREQ_JA}_nsites{NSITES_JA}"

# Ensure output folders exist (important on HPC scratch nodes)
checkpoint_path = TRACE_DIR / f"checkpoint_{filename_save}.joblib"

ROAD='NoRoad'
AREA=AREA_JA
NSITES = NSITES_JA  # number of sites to choose for surveillance
SURVEY_FREQ=SURVEY_FREQ_JA

###############################################################################
####################### RUN OPTIMISATION ######################################
###############################################################################

### start time
start_time = datetime.datetime.now()
print('START TIME:', start_time, flush=True)

### Set seed to ensure reproducability
#seed_used=0
seed_used=np.random.choice(np.arange(10000) )
np.random.seed(seed_used) 

### Read simulation data
sim_data = load(SIM_OUTPUT_DIR / filename_sim)

print(f"seed used:{seed_used}, num of simulations:{len(sim_data)}", flush=True)
print(f"{filename_save}, P(detect)={P_DETECT}, #plants surveyed={NTREES_SURVEY}", flush=True)
print(f'alpha, beta, sigma0, logistic rate, prev are: {ALPHA}, {BETA}, {SIGMA0}, {LOGISTIC_RATE}, {PREVALENCE}', flush=True)

### column bind the x and y coords of the points with hosts >=0 (max of 2500 of them (50x50))
host_xpos = sim_data[0]['x']
host_ypos = sim_data[0]['y']
host_positions = np.column_stack((host_xpos, host_ypos))
host_population=sim_data[0]['host_population']

### Obtain site allowed
site_loc_allowed_ID, cells_near_road_ID = site_loc_allowed(roadnetwork=None, host_pos=host_positions, host_pop=host_population, accessible_dist=1000)  # 1km accessibility


### initial config (location of the surveillance sites). Set randomly (within road constraints) ================================

config0 = np.random.choice(site_loc_allowed_ID, size=min(len(site_loc_allowed_ID), NSITES), replace=False)  # choose sites randomly from the allowed locations
print('initial config:', config0, flush=True)

### check if len(config0) < len(site_loc_allowed_ID)
print("Check validity of initial config0:", len(config0) < len(site_loc_allowed_ID), flush=True)


### Optimisation (SA) ===========================================================================================================
n_iter =50000 # 
temperature = 10  # find how to set initial temperature!!!!!!!!!!
cooling_rate = 0.9995 # # find how to set cooling rate!!!!!!!!!!
print(f'number of SA trials: {n_iter}, \tstarting temp:{temperature}, \tcooling rate:{cooling_rate}')

best_config, config_list, temp_list, objVal_list, n_iter_actual = simulated_annealing(data_sim=sim_data, 
                                                                        obj_fun=objective_more_optimised, 
                                                                        site_loc_allowed=site_loc_allowed_ID, 
                                                                        config0=config0,
                                                                        n_iterations=n_iter, 
                                                                        init_temperature=temperature, 
                                                                        cooling_rate=cooling_rate,
                                                                        ntrees_survey=NTREES_SURVEY,
                                                                        P_detect=P_DETECT, 
                                                                        survey_freq=SURVEY_FREQ,
                                                                        lastN=10000,earlystop_tol=0.0001,
                                                                        checkpoint_path=checkpoint_path,
                                                                        checkpoint_every=500,
                                                                        resume=True) #smaller tolerance



road_length, road_coverage_area, RCAP,road_coverage_plant,RMS_toRoad_wtd,RMS_toRoad, RMS_toAllowed_wtd, RMS_toAllowed, RMS_toOpt_wtd, RMS_toOpt,num_red_optimal, num_red_allowed, prop_red_allowedred,prop_red_allowed = opt_metrics(None, host_positions, host_population, best_config)

metric = {'alpha': ALPHA,
          'beta': BETA,
          'sigma0': SIGMA0,
          'logistic_rate':LOGISTIC_RATE ,
          'prevalence': PREVALENCE,
          'Pdetect': P_DETECT,
          'ntrees_survey': NTREES_SURVEY,
          'road': ROAD,
          'area': AREA,
          'surveyfreq': SURVEY_FREQ,
          'nsites': NSITES,
          'seed_opt': seed_used,
          'num_host_pop_non0': np.sum(host_population>0),
          'sites_allowed': site_loc_allowed_ID,
          'config_init': config0,
          'config_opt': best_config,
          'n_iter_actual': n_iter_actual,
          'road_length': road_length,
          'road_coverage_area': road_coverage_area,
          'RCAP': RCAP,
          'road_coverage_plant': road_coverage_plant,
          'RMS_toRoad_wtd': RMS_toRoad_wtd,
          'RMS_toRoad': RMS_toRoad,
          'RMS_toAllowed_wtd': RMS_toAllowed_wtd, 
          'RMS_toAllowed': RMS_toAllowed,
          'RMS_toOpt_wtd': RMS_toOpt_wtd,
          'RMS_toOpt': RMS_toOpt,
          'num_red_optimal': num_red_optimal,
          'num_red_allowed': num_red_allowed,
          'prop_red_allowedred': prop_red_allowedred,
          'prop_red_allowed': prop_red_allowed,
          'objective': objVal_list[-1]
          }



print(f"best config:{best_config}, \nhost population of the best config: {host_population[best_config]}", flush=True)
print(f"best_objective:{objVal_list[-1]}")

### Save data
dump(objVal_list, TRACE_DIR / f"trace_objval_{filename_save}.joblib")
dump(config_list, CONFIG_DIR / f"config_{filename_save}.joblib")
dump(metric, METRIC_DIR / f"metric_{filename_save}.joblib")
###############

end_time = datetime.datetime.now()
print("End time:", end_time, flush=True)
print("Time taken for simulation:", end_time - start_time, flush=True)
#==================================================================================================================================


### Plot trace of objective value
fig, ax = plt.subplots(figsize = (10,6))
plt.plot(objVal_list , label = '')
##plt.xscale('log', base = 10)
plt.xlabel('Trial')
plt.ylabel('Objective value')
plt.title(f'Trace of SA ({n_iter} trials, start temp={temperature}, cooling rate={cooling_rate}), {filename_save}')
## plt.legend()
plt.savefig(os.path.join(cwd, save_dir_trace, f'plot_OptTrace_{filename_save}.pdf'), dpi=600)
plt.clf # clear figure
plt.close(fig)


### Plot optimisation result
fig, ax = plt.subplots(figsize = (15,15))
fig0=ax.scatter(host_positions[:, 0] ,host_positions[:, 1],  marker='s', s=30, linewidths=0, edgecolors='none', alpha=0.7, c=host_population, cmap='RdYlGn_r')
fig.colorbar(fig0, ax=ax, label='number of plants in cell', pad=0.005)
ax.scatter(host_positions[best_config, 0], host_positions[best_config, 1], marker='x', s=20, c='black', label='optimal sites', alpha=0.6)
plt.xlabel('x')
plt.ylabel('y')
plt.title(f'{filename_save}')
plt.legend()
plt.savefig(os.path.join(cwd, save_dir_map, f'plot_OptResult_{filename_save}.pdf'), dpi=600)
plt.clf # clear figure
plt.close(fig)




















