"""
VARIANCE DECOMPOSITION AND BOOTSTRAP RANK STABILITY (Reviewer 1, comment 6)

Uses the stored simulations and optimisation outputs at baseline
(N = 10 sites, F = 52 weeks) for all 144 study areas (136 accessibility-
constrained plus 8 unconstrained). No new optimisation is run.

(a) Variance decomposition
    For each study area, ~30 configurations are sampled along the simulated
    annealing trace, from early to late. Each configuration's objective is
    estimated as the mean of its per-simulation detection probabilities.
    The variance of these estimates across configurations is split into:
        Monte Carlo variance  = mean over configs of Var_s(P_s) / M
        genuine variance      = observed variance - Monte Carlo variance
    The fraction attributable to genuine differences between configurations
    is reported.

(b) Near-optimal neighbourhood
    For the optimal configuration, 20 neighbours are generated by swapping
    one site for another accessible cell. For each neighbour:
      - the paired difference (optimum minus neighbour) is computed over the
        same 2,000 simulations, with its standard error and z-score
      - the simulations are bootstrap-resampled 1,000 times, and the
        proportion of resamples in which the optimum remains best is recorded

Detection applies to symptomatic plants only, as in the corrected analysis.

    python variance_bootstrap.py
"""

import os
import gc
import numpy as np
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt
from matplotlib import font_manager
from joblib import load

from pathlib import Path

# ==========================================================================
# All paths are resolved relative to the repository root.
THIS_FILE = Path(__file__).resolve()
PROJECT_ROOT = THIS_FILE.parents[3]

OUTPUTS   = PROJECT_ROOT / "main_analysis" / "Outputs"
DIR_SIMS  = OUTPUTS / "simulations"
DIR_OPT   = OUTPUTS / "optimisation"
DIR_DISTR = PROJECT_ROOT / "main_analysis" / "host_distributions"
DIR_OUT   = OUTPUTS / "figures"
# ==========================================================================

SIM_DIR    = DIR_SIMS
DIR_METRIC = DIR_OPT / "output_metric_sfreq52_nsite10"
DIR_CONFIG = DIR_OPT / "output_config"
OUT_DIR    = DIR_OUT

OUT_CSV = os.path.join(OUT_DIR, "FigureS7_variance_bootstrap.csv")
OUT_PNG = os.path.join(OUT_DIR, "FigureS7.png")

N_TRACE_CONFIGS = 30      # configurations sampled along each SA trace
N_NEIGHBOURS = 20         # single-swap neighbours of each optimum
N_BOOT = 1000             # bootstrap resamples
SEED = 0
# ==========================================================================

SURVEY_FREQ = 52
NSITES = 10
NTREES_SURVEY = 30
P_DETECT = 0.75
SIGMA0 = 0.01
LOGISTIC_RATE = 0.1693

AREAS = [f"{i:02d}" for i in range(1, 9)]
ROADS = ([f"01_{i}" for i in range(5)] + [f"02_{i}" for i in range(3)] +
         [f"03_{i}" for i in range(6)] + [f"05_{i}" for i in range(3)])

OUT_DIR.mkdir(parents=True, exist_ok=True)
rng = np.random.default_rng(SEED)


def set_font(preferred="CMU Serif"):
    available = {f.name for f in font_manager.fontManager.ttflist}
    for c in [preferred, "Latin Modern Roman", "DejaVu Serif"]:
        if c in available:
            mpl.rcParams['font.family'] = 'serif'
            mpl.rcParams['font.serif'] = [c]
            mpl.rcParams['mathtext.fontset'] = 'cm'
            return


set_font()
for k in ['font.weight', 'axes.titleweight', 'axes.labelweight']:
    mpl.rcParams[k] = 500
mpl.rcParams['font.size'] = 11


# ------------------------------------------------ fast evaluator per area
class Evaluator:
    """Precomputes per-simulation quantities so configurations evaluate fast.
    Reproduces objective_more_optimised() with symptomatic-only detection."""

    def __init__(self, sim_data):
        self.M = len(sim_data)
        self.host_pop = np.asarray(sim_data[0]['host_population'])
        self.mtrees_all = np.clip(self.host_pop, 1, NTREES_SURVEY)

        self.time_C2I = [np.asarray(s['time_1st_C2I']) for s in sim_data]
        self.infected = np.array([np.asarray(s['state']) != 'S'
                                  for s in sim_data])
        self.survey_times = []
        for s in sim_data:
            t1 = np.asarray(s['time_1st_S2C']); t2 = np.asarray(s['time_1st_C2I'])
            t_star = np.max(np.concatenate([t1[t1 != np.inf], t2[t2 != np.inf]]))
            self.survey_times.append(np.arange(0, t_star, SURVEY_FREQ))

    def per_sim(self, config):
        config = np.asarray(config)
        P = np.zeros(self.M)
        mtrees = self.mtrees_all[config]
        overlap = self.infected[:, config].any(axis=1)
        for s in np.where(overlap)[0]:
            t = self.survey_times[s]
            t_diff = t[:, None] - self.time_C2I[s][config][None, :]
            t_diff[t_diff < 0] = -np.inf
            prop_I = 1 / (1 + (1 / SIGMA0 - 1) * np.exp(-LOGISTIC_RATE * t_diff))
            P[s] = 1 - np.prod((1 - P_DETECT * prop_I) ** mtrees)
        return P


def sample_trace_configs(config_list, n):
    """Unique configurations spread evenly along the SA trace."""
    arr = np.vstack([np.sort(np.asarray(c)) for c in config_list])
    _, first_idx = np.unique(arr, axis=0, return_index=True)
    first_idx = np.sort(first_idx)
    if len(first_idx) <= n:
        chosen = first_idx
    else:
        chosen = first_idx[np.linspace(0, len(first_idx) - 1, n).astype(int)]
    return [arr[i] for i in chosen]


def neighbours(opt, allowed, n):
    """Distinct configurations differing from opt by one site."""
    opt = np.asarray(opt)
    pool = np.setdiff1d(allowed, opt)
    if len(pool) == 0:
        return []
    out, seen, tries = [], set(), 0
    while len(out) < n and tries < 20 * n:
        tries += 1
        c = opt.copy()
        c[rng.integers(len(c))] = rng.choice(pool)
        key = tuple(np.sort(c))
        if key not in seen:
            seen.add(key)
            out.append(c)
    return out


# ---------------------------------------------------------------- run
rows = []

for area in AREAS:
    print(f"\n=== area {area}: loading simulations ...", flush=True)
    sim_data = load(os.path.join(SIM_DIR, f"df_sims{area}.joblib"))
    ev = Evaluator(sim_data)
    del sim_data
    gc.collect()

    for road in ROADS + ["NoRoad"]:
        tag = (f"NoRoad_area{area}" if road == "NoRoad"
               else f"road{road}_area{area}")
        stem = f"{tag}_surveyfreq{SURVEY_FREQ}_nsites{NSITES}"

        m = load(os.path.join(DIR_METRIC, f"metric_{stem}.joblib"))
        allowed = np.asarray(m['sites_allowed'])
        opt = np.asarray(m['config_opt'])
        forced = len(allowed) <= NSITES

        row = {'area': area, 'road': road, 'n_allowed': len(allowed),
               'forced': forced, 'objective_stored': m['objective']}

        # ---- (a) variance decomposition along the SA trace
        config_list = load(os.path.join(DIR_CONFIG, f"config_{stem}.joblib"))
        trace_cfgs = sample_trace_configs(config_list, N_TRACE_CONFIGS)
        if len(trace_cfgs) >= 3:
            Pmat = np.vstack([ev.per_sim(c) for c in trace_cfgs])
            J = Pmat.mean(axis=1)
            var_obs = J.var(ddof=1)
            var_mc = np.mean(Pmat.var(axis=1, ddof=1) / ev.M)
            var_gen = max(var_obs - var_mc, 0.0)
            row.update({
                'n_trace_configs': len(trace_cfgs),
                'var_observed': var_obs,
                'var_mc': var_mc,
                'frac_genuine': var_gen / var_obs if var_obs > 0 else np.nan,
                'snr': var_gen / var_mc if var_mc > 0 else np.nan,
            })

        # ---- (b) near-optimal neighbourhood
        nbrs = [] if forced else neighbours(opt, allowed, N_NEIGHBOURS)
        if nbrs:
            P_opt = ev.per_sim(opt)
            P_nbr = np.vstack([ev.per_sim(c) for c in nbrs])

            D = P_opt[None, :] - P_nbr                   # paired differences
            d_mean = D.mean(axis=1)
            d_se = D.std(axis=1, ddof=1) / np.sqrt(ev.M)
            with np.errstate(divide='ignore', invalid='ignore'):
                z = np.where(d_se > 0, d_mean / d_se, np.inf)

            # unpaired SE of the difference, for comparison
            se_unpaired = np.sqrt(P_opt.var(ddof=1) / ev.M +
                                  P_nbr.var(axis=1, ddof=1) / ev.M)

            # bootstrap: resample simulations with replacement
            allP = np.vstack([P_opt, P_nbr])
            counts = rng.multinomial(ev.M, np.full(ev.M, 1 / ev.M), size=N_BOOT)
            boot_means = allP @ counts.T / ev.M          # (configs, N_BOOT)
            opt_best = np.mean(np.argmax(boot_means, axis=0) == 0)

            row.update({
                'n_neighbours': len(nbrs),
                'n_nbr_better_full': int(np.sum(d_mean < 0)),
                'min_diff': d_mean.min(),
                'median_diff': np.median(d_mean),
                'min_z': z[np.isfinite(z)].min() if np.isfinite(z).any() else np.nan,
                'median_z': np.median(z[np.isfinite(z)]) if np.isfinite(z).any() else np.nan,
                'se_ratio_paired_over_unpaired':
                    np.median(d_se / se_unpaired),
                'boot_opt_best': opt_best,
            })

        rows.append(row)
        msg = f"  {stem:45s}"
        if 'frac_genuine' in row:
            msg += f" genuine={row['frac_genuine']:.3f}"
        if 'boot_opt_best' in row:
            msg += (f"  boot_best={row['boot_opt_best']:.3f}"
                    f"  nbr_better={row['n_nbr_better_full']}"
                    f"  min_z={row['min_z']:.1f}")
        if forced:
            msg += "  [forced - no neighbours]"
        print(msg, flush=True)

    del ev
    gc.collect()

df = pd.DataFrame(rows)
df.to_csv(OUT_CSV, index=False)

# ---------------------------------------------------------------- summary
print("\n" + "=" * 72)
print("SUMMARY")
print("=" * 72)

a = df.dropna(subset=['frac_genuine'])
print(f"(a) variance decomposition, {len(a)} study areas")
print(f"    fraction of variance from genuine configuration differences:")
print(f"      median {a['frac_genuine'].median():.4f}, "
      f"minimum {a['frac_genuine'].min():.4f}, "
      f"5th percentile {a['frac_genuine'].quantile(0.05):.4f}")
print(f"    signal-to-noise ratio: median {a['snr'].median():.0f}, "
      f"minimum {a['snr'].min():.0f}")

b = df.dropna(subset=['boot_opt_best'])
print(f"\n(b) near-optimal neighbourhood, {len(b)} study areas "
      f"({int(df['forced'].sum())} forced cases excluded)")
print(f"    bootstrap: optimum remained best in")
print(f"      median {100*b['boot_opt_best'].median():.1f}% of resamples, "
      f"minimum {100*b['boot_opt_best'].min():.1f}%")
print(f"      >=95% of resamples in {int((b['boot_opt_best']>=0.95).sum())}"
      f"/{len(b)} study areas")
print(f"    neighbours outperforming the stored optimum at full M: "
      f"{int(b['n_nbr_better_full'].sum())} of "
      f"{int(b['n_neighbours'].sum())} tested, in "
      f"{int((b['n_nbr_better_full']>0).sum())} study areas")
print(f"    paired z of optimum over neighbours: "
      f"median of per-area medians {b['median_z'].median():.1f}")
print(f"    paired SE as a fraction of unpaired SE: "
      f"median {b['se_ratio_paired_over_unpaired'].median():.3f}")

# ---------------------------------------------------------------- figure
fig, axes = plt.subplots(1, 2, figsize=(11, 4.2), dpi=300)

axes[0].hist(a['frac_genuine'], bins=30, color='C0', edgecolor='white')
axes[0].set_xlabel('Fraction of variance from genuine\nconfiguration differences')
axes[0].set_ylabel('Number of study areas')

axes[1].hist(b['boot_opt_best'], bins=30, color='C1', edgecolor='white')
axes[1].set_xlabel('Proportion of bootstrap resamples in\nwhich the optimum remains best')

for ax, letter in zip(axes, 'ab'):
    ax.spines[['top', 'right']].set_visible(False)
    ax.text(-0.14, 1.06, f"{letter}.", transform=ax.transAxes,
            fontsize=15, fontweight=700, va='top', ha='left')

fig.tight_layout()
fig.savefig(OUT_PNG)
print(f"\nSaved {OUT_PNG}\n      {OUT_CSV}")
